baseURL: http://www.example.com
title: Joel Burbano
theme: hugo-coder
languageCode: en
defaultContentLanguage: en 
paginate: 20
enableEmoji: yes
markup:
  highlight:
    noClasses: no
params:
  author: Joel Burbano
  avatarURL: images/joeb.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Joel's personal site
  hideColorSchemeToggle: no
  info:
    - Mathematical Engineer
    - Data Scientist
    - Statistical
  keywords: blog
  maxSeeAlsoItems: 5
  rtl: no
  since: 
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: 
      weight: 1
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/joel-burbano-849120230/
      weight: 4
    # - icon: fa fa-2x fa-medium
    #   name: Medium
    #   url: https://medium.com/@johndoe
    #   weight: 5
    # 
    - icon: fa fa-2x fa-whatsapp
      name: WhatsApp
      url: https://wa.me/593997868351
      weight: 6
    - icon: fa fa-2x fa-envelope
      name: Correo
      mailto: joelburbano@outlook.com
      weight: 6
    
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':us:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact me
          url: contact/
          weight: 5
  es:
    languageName: ':es:'
    menu:
      main:
        - name: Acerca de
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Proyectos
          url: projects/
          weight: 3
        - name: Contato
          url: contact/
          weight: 5
    params:
      author: Joel Burbano
      description: Sitio personal de Joel Burbano
      info: 
        - Ingeniero Matemático
        - Cientifico de Datos
        - Estadístico
      keywords: blog
    title: Joel Burbano
