baseURL: https://joel-x.github.io/blog_jxbs/
publishDir: docs
title: Joel Burbano
theme: hugo-coder

languageCode: es
defaultContentLanguage: es
paginate: 20
enableEmoji: yes
markup:
  highlight:
    noClasses: no
params:
  clearReading: false
  sidebarBehavior: 1
  math: true
  katex: true
  author: Joel Burbano
  avatarURL: images/joeb.jpg
  colorScheme: auto
  commit: 
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Sitio personal de Joel
  hideColorSchemeToggle: no
  info:
    - Ingeniero Matemático
    - Análista de Datos
    - Científico de Datos
    - Estadístico
  keywords: blog personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/joel-x
      weight: 1
    - icon: fa fa-2x fa-whatsapp
      name: Whatsapp
      url: https://wa.me/593997868351
      weight: 3
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/joel-burbano-849120230/
      weight: 4
    - icon: fa fa-2x fa-envelope
      name: Medium
      url: mailto:joelburbano@outlook.com
      weight: 5

taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  es:
    languageName: ':es:'
    menu:
      main:
        - name: Acerca de
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Proyectos
          url: projects/
          weight: 3
        - name: Contacto
          url: contact/
          weight: 5
  us:
    languageName: ':us:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contat me
          url: contact/
          weight: 5
    params:
      author: Joel Burbano
      description: Joel's personal site
      info: 
          - Mathematical Engineer
          - Data Analyst
          - Data Scientist
          - Statistical
      keywords: personal blog
    title: Joel Burbano
